DISPLAY_FABRIC_TYPE_MAP: dict[str, str] = {
    "vxlanIbgp": "Data Center VXLAN EVPN - iBGP",
    "vxlanEbgp": "Data Center VXLAN EVPN - eBGP",
    "vxlanCampus": "Campus VXLAN EVPN",
    "aimlVxlanIbgp": "AI/ML VXLAN EVPN - iBGP",
    "aimlVxlanEbgp": "AI/ML VXLAN EVPN - eBGP",
    "aimlRouted": "AI/ML Routed",
    "routed": "Routed",
    "classicLan": "Classic LAN",
    "classicLanEnhanced": "Enhanced Classic LAN",
    "ipfm": "IPFM",
    "ipfmEnhanced": "Enhanced IPFM",
    "ipfmGenericMulticast": "IPFM Generic Multicast",
    "externalConnectivity": "External Connectivity",
    "vxlanExternal": "VXLAN External",
    "aci": "ACI",
    "meta": "Meta",
    "dataBroker": "Data Broker",
}
